# Generated by Django 4.2.3 on 2023-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=None, upload_to='D:\\Document\\dai-hoc\\thuong-mai-dien-tu\\website\\ecommerce\\media/'),
        ),
    ]
