# Generated by Django 4.2.3 on 2023-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='D:\\Document\\dai-hoc\\thuong-mai-dien-tu\\website\\ecommerce\\media//default.jpg', upload_to='D:\\Document\\dai-hoc\\thuong-mai-dien-tu\\website\\ecommerce\\media/'),
        ),
    ]
