# Generated by Django 4.2.3 on 2023-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='items/default.jpg', null=True, upload_to='items/'),
        ),
    ]
