# Generated by Django 4.2.3 on 2023-08-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='items/default.jpg', null=True, upload_to='items/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
