# Generated by Django 4.2.3 on 2023-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_item_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='media/items/default.jpg', null=True, upload_to='media/items/'),
        ),
    ]
