# Generated by Django 4.2.3 on 2023-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='market/media/items/default.jpg', null=True, upload_to='market/media/items/'),
        ),
    ]
