# Generated by Django 4.2.3 on 2023-08-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_item_start_date_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
