# Generated by Django 4.2.3 on 2023-08-06 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_item_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='start_date',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 1, 1, 0, 0, 1)),
            preserve_default=False,
        ),
    ]
