# Generated by Django 4.2.3 on 2023-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_remove_item_start_date_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(),
        ),
    ]
