# Generated by Django 4.2.3 on 2023-08-06 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 8, 6, 16, 5, 14, 143754)),
        ),
    ]
