# Generated by Django 4.2.3 on 2023-08-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_item_recently'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
